### ISSUE TITLE
Invalid return type

### ISSUE THREAD

**Issue by richard-parnaby-king** [cardstream/Magento-Unbranded#1]
Using Magento Commerce on Cloud 2.3.5-p2 and placing a test transaction with the below credentials I am getting an "Invalid return type" exception message. After some digging, it looks like Magento is looking for a response of type "ResultInterface" or "HttpInterface" (\Magento\Framework\App\Http line 124) but the controller P3\PaymentGateway\Controller\Order\Process is not returning one of these.

#### Test credentials
Gateway Url: https://gateway.retailmerchantservices.co.uk/direct/ 
Merchant ID : 101600
Signature Key : Offer37Fresh7Blame

#### Test Card Details 
Card Number : 4543 0599 9999 9982
CVV Number : 110

#### Exception Message
```
{
    "0":"Invalid return type",
    "1":"
        #1 Magento\Framework\App\Http\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]
        #2 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]
        #3 Magento\Framework\App\Http\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:26]
        #4 Magento\Framework\App\Http\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]
        #5 Magento\Framework\App\Bootstrap->run() called at [pub\/index.php:40]
    ",
    "url":"\/paymentgateway\/order\/process",
    "script_name":"\/index.php",
    "report_id":"117222931cb5c62cfb1ec7a4e7026c174ed90e1d9a8d9ec7431d27620e254e5e"
}
```

**Comment by uktakepayments** [comment]
Hello, 
The plugin seems to have a couple of issues in relation to empty return values in the "public static function processResponse".
(file: Gateway.php)

Also, I found out that the module cuts off after comma values (pens, cents, pennies) in:
"public function captureOrder"
line 269 it says:
` $amount = (int) round($order->getBaseTotalDue(), 2) * 100;`

It should be:
` $amount = $order->getBaseTotalDue();`

Ideally you would want to ensure only numbers are being taken by the variable with:
`$amount = preg_replace('/[^0-9]/', '', $order->getBaseTotalDue());`

Last but not least, if none of the issues above prevent the module from working correctly the module doesn't trigger a payment result page / message on Magento 2 front end for customers which also indicates that the module may return empty values.
Please can these issues be addressed and fixed?

**Comment by cardstreamltd** [comment]
Hello,

Thank you for contacting us.

Please send an email of the issue to solutions@cardstream.com so can can review and advise.

Kind regards,
Cardstream
